SnapVoteBookGram/Controllers/ElectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SnapVoteBookGram.Data;
using SnapVoteBookGram.Models;
using SnapVoteBookGram.Models.ElectionViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SnapVoteBookGram.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ElectionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ElectionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Elections
        public async Task<IActionResult> Index()
        {
            var viewModel = new ElectionsIndexData();
            viewModel.Elections = await _context.Elections
                  .Include(i => i.ElectionBallotAssignments)
                    .ThenInclude(i => i.Ballot)
                  .AsNoTracking()
                  .ToListAsync();

            return View(viewModel);
        }

        // GET: Elections/Create
        public IActionResult Create()
        {
            var election = new Election();
            PopulateAssignedBallotData(election);
            return View();
        }

        // POST: Elections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Begin,End")] Election election, string[] selectedBallots)
        {
            if (selectedBallots != null)
            {
                election.ElectionBallotAssignments = new List<ElectionBallotAssignment>();
                foreach (var ballot in selectedBallots)
                {
                    var ballotToAdd = new ElectionBallotAssignment { ElectionId = election.Id, BallotId = int.Parse(ballot) };
                    election.ElectionBallotAssignments.Add(ballotToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(election);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            PopulateAssignedBallotData(election);
            return View(election);
        }

        // GET: Elections/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var election = await _context.Elections
                .Include(i => i.ElectionBallotAssignments).ThenInclude(i => i.Ballot)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.Id == id);
            if (election == null)
            {
                return NotFound();
            }

            PopulateAssignedBallotData(election);
            return View(election);
        }

        // POST: Elections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, string[] selectedBallots)
        {
            if (id == null)
            {
                return NotFound();
            }

            var electionToUpdate = await _context.Elections
                .Include(i => i.ElectionBallotAssignments)
                    .ThenInclude(i => i.Ballot)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (await TryUpdateModelAsync<Election>(electionToUpdate, "", i => i.Title, i => i.Begin, i => i.End))
            {
                UpdateBallots(selectedBallots, electionToUpdate);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "There was a problem saving your changes. Please try again.");
                }
                return RedirectToAction(nameof(Index));
            }
            UpdateBallots(selectedBallots, electionToUpdate);
            PopulateAssignedBallotData(electionToUpdate);
            return View(electionToUpdate);
        }

        // GET: Elections/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var election = await _context.Elections
                .SingleOrDefaultAsync(m => m.Id == id);
            if (election == null)
            {
                return NotFound();
            }

            return View(election);
        }

        // POST: Elections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var election = await _context.Elections.SingleOrDefaultAsync(m => m.Id == id);
            _context.Elections.Remove(election);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ElectionExists(int id)
        {
            return _context.Elections.Any(e => e.Id == id);
        }

        private void PopulateAssignedBallotData(Election election)
        {
            var allBallots = _context.Ballots;
            var currentBallots = new HashSet<int>(election.ElectionBallotAssignments.Select(c => c.BallotId));
            var viewModel = new List<AssignedBallotData>();
            foreach (var ballot in allBallots)
            {
                viewModel.Add(new AssignedBallotData
                {
                    BallotId = ballot.Id,
                    Title = ballot.Title,
                    Assigned = currentBallots.Contains(ballot.Id)
                });
            }
            ViewData["Ballots"] = viewModel.OrderBy(i => i.Title).ToList();
        }

        private void UpdateBallots(string[] selectedBallots, Election electionToUpdate)
        {
            if (selectedBallots == null)
            {
                electionToUpdate.ElectionBallotAssignments = new List<ElectionBallotAssignment>();
                return;
            }

            var selectedBallotsHashSet = new HashSet<string>(selectedBallots);
            var currentBallots = new HashSet<int>(electionToUpdate.ElectionBallotAssignments.Select(c => c.Ballot.Id));

            foreach (var ballot in _context.Ballots)
            {
                if (selectedBallotsHashSet.Contains(ballot.Id.ToString()))
                {
                    if (!currentBallots.Contains(ballot.Id))
                    {
                        electionToUpdate.ElectionBallotAssignments.Add(new ElectionBallotAssignment { ElectionId = electionToUpdate.Id, BallotId = ballot.Id });
                    }
                }
                else
                {
                    if (currentBallots.Contains(ballot.Id))
                    {
                        ElectionBallotAssignment ballotToRemove = electionToUpdate.ElectionBallotAssignments.SingleOrDefault(i => i.BallotId == ballot.Id);
                        _context.Remove(ballotToRemove);
                    }
                }
            }
        }

    }
}

SnapVoteBookGram/Controllers/VotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SnapVoteBookGram.Data;
using SnapVoteBookGram.Models;
using SnapVoteBookGram.Models.ElectionViewModels;
using SnapVoteBookGram.Models.VoteViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SnapVoteBookGram.Controllers
{
    public class VotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Elections
        public async Task<IActionResult> Elections()
        {
            var viewModel = new ElectionsIndexData();
            viewModel.Elections = await _context.Elections
                .Where(i => i.End > DateTime.Now)
                  .AsNoTracking()
                  .ToListAsync();

            return View(viewModel);
        }

        // GET: ElectionBallots
        public async Task<IActionResult> ElectionBallots(int? id)
        {
            //get current userId
            ClaimsPrincipal currentUser = User;
            var userId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            ViewData["ElectionId"] = id.Value;

            var viewModel = new ElectionBallotsIndexData();
            
            var data = await _context.Elections
                .Include(i => i.ElectionBallotAssignments)
                    .ThenInclude(b => b.Ballot)
                        .ThenInclude(o => o.BallotOptionAssignments)
                            .ThenInclude(p => p.BallotOption).AsNoTracking().ToListAsync();

            viewModel.Election = data
                .Where(i => i.Id == id.Value).Single();

            var BallotsUserHasVotedIn = await _context.Votes
                .Where(v => v.ApplicationUserId == userId)
                .Select(v => v.BallotId)
                .ToListAsync();

            //only display ballots for election that user hasn't already voted in
            viewModel.Ballots = viewModel.Election.ElectionBallotAssignments
                .Select(o => o.Ballot)
                .Where(i => !BallotsUserHasVotedIn.Contains(i.Id))
                .ToList();

            return View(viewModel);
        }

        // GET: ElectionBallotOptions
        public async Task<IActionResult> ElectionBallotOptions(int? electionId, int? ballotId)
        {
            ViewData["ElectionId"] = electionId.Value;
            ViewData["BallotId"] = ballotId.Value;

            var viewModel = new ElectionBallotOptionsData();

            var data = await _context.Elections
                .Include(i => i.ElectionBallotAssignments)
                    .ThenInclude(b => b.Ballot)
                        .ThenInclude(o => o.BallotOptionAssignments)
                            .ThenInclude(p => p.BallotOption).AsNoTracking().ToListAsync();

            viewModel.Election = data
                .Where(i => i.Id == electionId.Value).Single();

            viewModel.Ballot = viewModel.Election.ElectionBallotAssignments
                .Where(b => b.BallotId == ballotId.Value).Single().Ballot;

            viewModel.BallotOptions = viewModel.Ballot.BallotOptionAssignments
                .Select(o => o.BallotOption).ToList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Vote(int? electionId, int? ballotId, string[] selectedBallotOptions, string[] selectedBallotOptionValues)
        {
            //get current userId
            ClaimsPrincipal currentUser = User;
            var userId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            //get current ballot
            Ballot selectedBallot = _context.Ballots
                    .Where(b => b.Id == ballotId.Value).Single();

            List<Vote> votesToSave = new List<Vote>();

            //generate vote for each ballot option
            for (int count = 0; count < selectedBallotOptions.Length; count++)
            {
                Vote vote = new Vote();
                
                //for ranked voting
                if (selectedBallot.BallotType == BallotType.Ranked)
                {
                    if (selectedBallotOptionValues != null && selectedBallotOptionValues.Length != 0 && selectedBallotOptionValues.Length >= count)
                    {
                        //only create vote if we have a valid rank value
                        int.TryParse(selectedBallotOptionValues[count], out int rank);
                        if (rank > 0)
                        {
                            vote = new Models.Vote()
                            {
                                ElectionId = electionId.Value,
                                BallotId = ballotId.Value,
                                BallotOptionId = int.Parse(selectedBallotOptions[count]),
                                ApplicationUserId = userId,
                                BallotOptionRank = rank
                            };
                            votesToSave.Add(vote);
                        }
                    }
                }
                //we don't have to worry about ranking for other ballot types
                else
                {
                    vote = new Models.Vote()
                    {
                        ElectionId = electionId.Value,
                        BallotId = ballotId.Value,
                        BallotOptionId = int.Parse(selectedBallotOptions[count]),
                        ApplicationUserId = userId
                    };
                    votesToSave.Add(vote);
                }
            }

            //save votes to database
            if (ModelState.IsValid && votesToSave.Count > 0)
            {
                _context.AddRange(votesToSave);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Elections));
        }

        // GET: Votes
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? electionId, int? ballotId)
        {
            var viewModel = new ResultsData();

            viewModel.Elections = await _context.Elections
                .Where(e => e.End < DateTime.Now)
                .Include(i => i.ElectionBallotAssignments)
                    .ThenInclude(b => b.Ballot)
                        .ThenInclude(o => o.BallotOptionAssignments)
                            .ThenInclude(p => p.BallotOption).AsNoTracking().ToListAsync();

            if (electionId != null)
            {
                ViewData["ElectionId"] = electionId.Value;
                viewModel.selectedElection = viewModel.Elections
                    .Where(e => e.Id == electionId.Value).Single();
                viewModel.Ballots = viewModel.selectedElection.ElectionBallotAssignments
                    .Select(o => o.Ballot).ToList();
            }

            if (ballotId != null)
            {
                ViewData["BallotId"] = ballotId.Value;
                viewModel.selectedBallot = viewModel.Ballots
                    .Where(b => b.Id == ballotId.Value).Single();

                //get all votes for current ballot
                var votes = await _context.Votes
                    .Where(e => e.ElectionId == electionId.Value)
                    .Where(b => b.BallotId == ballotId.Value)
                    .Include(o => o.BallotOption)
                    .ToListAsync();

                //sort votes rank for display
                if (viewModel.selectedBallot.BallotType == BallotType.Ranked)
                {

                    List<VoteRankResult> results = new List<VoteRankResult>();

                    var rankedVotes = votes
                        .GroupBy(g => g.BallotOptionRank).ToList();

                    foreach (var rank in rankedVotes)
                    {
                        VoteRankResult voteRankResult = new VoteRankResult()
                        {
                            Rank = rank.Key,
                            Votes = rank
                                .GroupBy(g => g.BallotOption)
                                .Select(group => new VoteResult
                                {
                                    Id = group.Key.Id,
                                    Description = group.Key.Description,
                                    Count = group.Count()
                                })
                                .OrderByDescending(x => x.Count).ToList()
                        };

                        results.Add(voteRankResult);
                    }

                    viewModel.RankedVotes = results;

                }
                //sort votes by count for display
                else
                {
                    viewModel.Votes = votes
                        .GroupBy(g => g.BallotOption)
                        .Select(group => new VoteResult
                        {
                            Id = group.Key.Id,
                            Description = group.Key.Description,
                            Count = group.Count()
                        })
                        .OrderByDescending(x => x.Count).ToList();
                }
            }

            return View(viewModel);
        }

        private bool VoteExists(int id)
        {
            return _context.Votes.Any(e => e.Id == id);
        }
    }
}

SnapVoteBookGram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnapVoteBookGram</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle snapvotebookgram-navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand snapvotebookgram-navbar-brand"><div class="wordart rainbow"><span class="text">SnapVoteBookGram</span></div></a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_NavigationPartial")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - SnapVoteBookGram</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SnapVoteBookGram/Views/Shared/_NavigationPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using SnapVoteBookGram.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="nav navbar-nav snapvotebookgram-navbar-list">
    @if (SignInManager.IsSignedIn(User))
    {
        if (User.IsInRole("Administrator"))
        {
            <li><a asp-area="" asp-controller="Elections" asp-action="Index">Elections</a></li>
            <li><a asp-area="" asp-controller="Ballots" asp-action="Index">Ballots</a></li>
            <li><a asp-area="" asp-controller="BallotOptions" asp-action="Index">Ballot Options</a></li>
        }
        else
        {
            <li><a asp-area="" asp-controller="Votes" asp-action="Elections">Cast Your Vote</a></li>
        }
    }
    <li><a asp-area="" asp-controller="Votes" asp-action="Index">Results</a></li>
</ul>